config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'pages#home'

  resources :comments, only: [:create, :destroy, :edit, :update]
  resources :posts, only: [:index, :show, :create, :destroy, :edit, :update] do
    member do
      post '/like', to: "likes#create", as: "like"
      delete '/like', to: "likes#destroy", as: "unlike"
    end
  end

  post '/follows', to: "follows#create", as: "follow"
  delete '/follows', to:"follows#destroy", as: "unfollow"

  get '/profile/:id', to: "users#show", as: "user"
  get '/profile/:id/following', to: "users#following", as: "following"
  get '/profile/:id/followers', to: "users#followers", as: "followers"
  post '/users/search', to: "users#search", as: :search
  get '/users/search', to: "users#search"

  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :read, :all
      can :manage, Post, user_id: user.id
      can :manage, Like, user_id: user.id
      can :manage, Comment, user_id: user.id
    end  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post, uniqueness: { scope: :user, mesage: "You already liked this post" }
  validates :post, :user, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  acts_as_commentable
  validates :user, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  has_many :posts
  has_many :likes

  acts_as_followable
  acts_as_follower

  validates :name, :description, presence: true
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post
  before_action :set_event, only: [:destroy]
  load_and_authorize_resource
  
  def create
    @like = Like.new(user: current_user, post: @post)
    respond_to do |format|
      if @like.save
        format.json { render json: @like }
        format.html { redirect_back fallback_location: root_path, notice: 'Post liked with success.' }
      else
        format.json { render json: @like.errors, status: :unprocessable_entity }
        format.html { redirect_back fallback_location: root_path }
      end
    end
  end

  def destroy
    @like.destroy

    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_back fallback_location: root_path, notice: 'Post unliked with success.' }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def set_event
      @like = Like.find_by(user: current_user, post: @post)
      @event = @like
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user        
    @post = Post.new
    posts = @user.posts.map {|post| post}
    @user.all_following.each { |user| user.posts.each{|post| posts << post } }
    @posts = (posts.sort_by! { |post| post.created_at }).reverse
    @posts = @posts.paginate(:page => (params[:page] || 1), :per_page => 20)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.json { render json: @post, status: :created }
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.js   { render :file => "/app/views/posts/show.js.erb" }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.html { redirect_to posts_path }
      end
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
    end
  end

  def edit
  end

  def update
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body).merge(user: current_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # load_and_authorize_resource
  before_action :set_user, only: [:show, :following, :followers]
  
  def show
    @posts = @user.posts
    @following = @user.following_users.limit(5)
    @followers = @user.followers_by_type('User').limit(5)
  end

  def following
    @following = @user.following_users
  end

  def followers
    @followers = @user.followers_by_type('User')
  end

  def search
    @user = current_user
    @query = User.ransack(params[:q])
    @users = @query.result(distinct: true)
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def liked?(user,post)
       user.likes.find_by(post_id: post.id) 
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Programmerhub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %>-<%= action_name %>">
    <header>
      <%= render "shared/navbar" %>
    </header>
    
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'red')" %>
      <% else message_type == 'notice' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'green')" %>
      <% end %>
    <% end %>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="row home">
  <div class="center">
    <h4 class="title">A Programmer Networking</h4>
    <h5 class="subtitle">Join to ProgrammerHub and connect with thousands of other software developers to learn and share</h5>

    <% if !current_user %>
      <%= link_to 'Join Now', new_user_registration_path, class: "btn btn-large grey darken-2 home-button"  %>
    <% end %>
  </div>
</div>

app/views/shared/_card-user.html.erb
<div class="row">
  <div class="card user-card">
    <div class="card-content">
      <div class="row">
        <div class="col s2 m2 l2">
          <img src="<%= user.avatar.thumb.url %>" alt="" class="circle responsive-img">
        </div>
        <div class="col s10 m10 l10">
          <div class="row">
            <p class="post-user-name">
              <%= link_to user.name, user_path(user.id) %>
            </p>
          </div>
          <div class="row">
            <p>
              <%= link_to truncate(user.description, length: 150), user_path(user), class: 'grey-text text-darken-2' %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="page-footer">
    <div class="container">
        <%# <div class="copyright">
            <b>
                <a class="copyright-link" href="/">
                    Created with<i class="material-icons copyright-icon">favorite</i>By OneBitCode
                </a>
            </b>
        </div> %>
    </div>
</div>

app/views/shared/_list-user.html.erb
<% users.each do |user| %>
  <%= render 'shared/card-user', user: user %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav">
    <div class="nav-wrapper col s12">
      <div class="container">
        <div class="row">
          <div class="col m3">
            <% if current_user %>
              <a href="/posts" class="brand-logo">
                <i class="material-icons">group</i>
                <span class="logo-title">
                  ProgrammerHub
                </span>
              </a>
            <% else %>
              <a href="/" class="brand-logo">
                <i class="material-icons">group</i>
                <span class="logo-title">
                  ProgrammerHub
                </span>
              </a>
            <% end %>
            <a href="#" data-activates="side-bar" class="button-collapse"><i class="material-icons">menu</i></a>
          </div>

          <ul class="right hide-on-med-and-down">
            <% if current_user %>
              <div class="row">
                <div class="col m7 offset-m3">
                  <li class="search-field">
                    <%= search_form_for @q, url: search_path do |f| %>
                      <%= f.search_field :name_cont, placeholder: "Search.." %>
                    <% end %>
                  </li>
                </div>
                <div class="col m2">
                  <li>
                    <a class="dropdown-button" href="#!" data-activates="dropdown1">
                      <img src="<%= current_user.avatar.thumb.url %>" alt="" class="responsive-img circle nav-image">
                    </a>
                  </li>
                </div>

                <ul id="dropdown1" class="dropdown-content">
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Config', edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </div>
            <% else %>
              <li><a href="/users/sign_in">Login</a></li>
              <li><a href="/users/sign_up">Register</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

<ul class="side-nav" id="side-bar">
  <% if current_user %>
    <li class="search-field">
      <%= search_form_for @q, url: search_path do |f| %>
        <%= f.search_field :name_cont, placeholder: "Search.." %>
      <% end %>
    </li>
    <li><%= link_to 'Feed', posts_path %></li>
    <li><%= link_to 'Profile', user_path(current_user) %></li>
    <li><%= link_to 'Config', edit_user_registration_path(current_user) %></li>
    <li><div class="divider"></div></li>
    <li>  <%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Log in</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Register</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>

app/views/shared/_post.html.erb
<div class="card hoverable" id="post_<%= post.id %>">
  <div class="card-content">
    <div class="row">
      <div class="col s2 m2 l2">
        <img src="<%= post.user.avatar.thumb.url %>" alt="" class="circle responsive-img left">
      </div>
      <div class="col s6 m6 l6">
        <p class="post-user-name"><%= link_to post.user.name, user_path(post.user_id) %></p>
      </div>
      <div class="col s3 m3 l3">
        <b class="post-date"><%= post.created_at.strftime("%Hh%M") %></b>
      </div>
      <% if current_user.id == post.user_id %>
        <div class="col s1 m1 l1">
          <%= link_to post_path(post), method: "delete", remote: true, class: 'delete_post', id: post.id do %>
            <i class="material-icons post-options">delete</i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col m12">
        <p class="post-body">
          <%= link_to truncate(post.body, length: 2000), post_path(post), class: 'grey-text text-darken-2' %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="post-actions">
        <%= link_to post_path(post) do %>
          <i class='material-icons action-link'>chat_bubble</i> <%= post.comments.count %>
        <% end %>
        <%= link_to unlike_post_path(post), method: "delete", remote: true, class: "unlike unlike_#{post.id}", id: post.id, style: "#{'display:none' unless liked?(current_user, post)}" do %>
          <i class="material-icons liked red-text">favorite</i>
        <% end %>
        <%= link_to like_post_path(post), method: "post", remote: true, class: "like like_#{post.id}", id: post.id, style: "#{'display:none' if liked?(current_user, post)}" do %>
          <i class="material-icons to-like">favorite</i>
        <% end %>
        <span class=<%= "like_count_#{post.id}" %>><%= post.likes.count %></span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user-info.html.erb
<div class="card user-info">
  <div class="card-content">
    <div class="row">
      <div class="user-info">
        <div class="col s4 m2 l4">
          <img src="<%= @user.avatar.thumb.url %>" alt="" class="circle responsive-img">
        </div>
        <div class="col s6 m6 l6">
          <p class="user-name"><%= link_to @user.name, user_path(@user) %></p>
        </div>
        <% if @user.id != current_user.id %>
          <% if current_user.following?(@user) %>
            <div class="col s2 m2 l2">
              <%= link_to unfollow_path(user_id: @user.id), method: :delete do %>
                <i class="material-icons btn-unfollow">grade</i>
              <% end %>
            </div>
          <% else %>
          <div class="col s2 m2 l2">
            <%= link_to follow_path(user_id: @user.id), method: :post do %>
              <i class="material-icons btn-follow">grade</i>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="divider"></div>
    <div class="row activity-info">
      <div class="col s4 m4 l4">
        <p class="center">Followers</p>
        <p class="center p-info"><%= link_to @user.followers_count, followers_path(@user) %></p>
      </div>
      <div class="col s4 m4 l4">
        <p class="center">Following</p>
        <p class="center p-info"><%= link_to @user.follow_count, following_path(@user) %></p>
      </div>
      <div class="col s4 m4 l4">
        <p class="center">Posts</p>
        <p class="center p-info" id="post_count"><%= link_to @user.posts.count, user_path(@user) %></p>
      </div>
    </div>
  </div>
</div>